# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Verify Java version
      run: java -version
    - name: Verify Maven Java version
      run: mvn -version
    - name: Extract project version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Build with Maven (including Linux app-image)
      run: mvn -B verify -P linux-package --file pom.xml
    - name: Zip app-image
      run: zip -r ejb-viewer-${{ env.VERSION }}-linux-app-image.zip target/dist/ejb-viewer/

    - name: Upload JAR to Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/ejb-viewer-${{ env.VERSION }}.jar
        asset_name: ejb-viewer-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive

    - name: Upload app-image to Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ejb-viewer-${{ env.VERSION }}-linux-app-image.zip
        asset_name: ejb-viewer-${{ env.VERSION }}-linux-app-image.zip
        asset_content_type: application/zip
